import React from 'react';

const Inventory = () => {
    return (
        <div>
            <h2>This is inventory page</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, doloribus laboriosam. Perspiciatis iste sed adipisci, repudiandae facere quisquam beatae! Commodi ducimus repellat atque delectus quidem laboriosam facere qui, laudantium inventore illum quae neque rem nam magni autem ipsum iusto, earum, porro velit assumenda ea! Sit, perferendis ut odit sint rem repellat ullam numquam id consectetur, necessitatibus nihil quia odio dolore quidem nobis suscipit voluptates. Officia qui, eius placeat ut explicabo porro cumque natus, quos doloribus consectetur non minima tempora assumenda labore repellendus tenetur eveniet sunt nam fugit suscipit dolores cupiditate perferendis quisquam? Ipsam perspiciatis aliquam ut cum dolore expedita in?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, doloribus laboriosam. Perspiciatis iste sed adipisci, repudiandae facere quisquam beatae! Commodi ducimus repellat atque delectus quidem laboriosam facere qui, laudantium inventore illum quae neque rem nam magni autem ipsum iusto, earum, porro velit assumenda ea! Sit, perferendis ut odit sint rem repellat ullam numquam id consectetur, necessitatibus nihil quia odio dolore quidem nobis suscipit voluptates. Officia qui, eius placeat ut explicabo porro cumque natus, quos doloribus consectetur non minima tempora assumenda labore repellendus tenetur eveniet sunt nam fugit suscipit dolores cupiditate perferendis quisquam? Ipsam perspiciatis aliquam ut cum dolore expedita in?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, doloribus laboriosam. Perspiciatis iste sed adipisci, repudiandae facere quisquam beatae! Commodi ducimus repellat atque delectus quidem laboriosam facere qui, laudantium inventore illum quae neque rem nam magni autem ipsum iusto, earum, porro velit assumenda ea! Sit, perferendis ut odit sint rem repellat ullam numquam id consectetur, necessitatibus nihil quia odio dolore quidem nobis suscipit voluptates. Officia qui, eius placeat ut explicabo porro cumque natus, quos doloribus consectetur non minima tempora assumenda labore repellendus tenetur eveniet sunt nam fugit suscipit dolores cupiditate perferendis quisquam? Ipsam perspiciatis aliquam ut cum dolore expedita in?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, doloribus laboriosam. Perspiciatis iste sed adipisci, repudiandae facere quisquam beatae! Commodi ducimus repellat atque delectus quidem laboriosam facere qui, laudantium inventore illum quae neque rem nam magni autem ipsum iusto, earum, porro velit assumenda ea! Sit, perferendis ut odit sint rem repellat ullam numquam id consectetur, necessitatibus nihil quia odio dolore quidem nobis suscipit voluptates. Officia qui, eius placeat ut explicabo porro cumque natus, quos doloribus consectetur non minima tempora assumenda labore repellendus tenetur eveniet sunt nam fugit suscipit dolores cupiditate perferendis quisquam? Ipsam perspiciatis aliquam ut cum dolore expedita in?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, doloribus laboriosam. Perspiciatis iste sed adipisci, repudiandae facere quisquam beatae! Commodi ducimus repellat atque delectus quidem laboriosam facere qui, laudantium inventore illum quae neque rem nam magni autem ipsum iusto, earum, porro velit assumenda ea! Sit, perferendis ut odit sint rem repellat ullam numquam id consectetur, necessitatibus nihil quia odio dolore quidem nobis suscipit voluptates. Officia qui, eius placeat ut explicabo porro cumque natus, quos doloribus consectetur non minima tempora assumenda labore repellendus tenetur eveniet sunt nam fugit suscipit dolores cupiditate perferendis quisquam? Ipsam perspiciatis aliquam ut cum dolore expedita in?</p>
        </div>
    );
};

export default Inventory;